"""
generate_wsi_clinical_reports.py
=================================
Generates WSI-style medical visualizations and clinical PDF reports for
the Onco-Fusion project, modelled after D:/Aakanksha/WSI/src/phase7_llm_report.py

New figures produced:
  figures/50_wsi_he_subtype_gallery.png   -- H&E tissue panels per subtype
  figures/51_wsi_patient_attention.png    -- Per-patient WSI patch-attention grids
  figures/52_wsi_gradcam_overlays.png     -- Simulated Grad-CAM on H&E tissue
  figures/53_multimodal_clinical.png      -- Multi-modal clinical dashboard

PDF clinical reports (fpdf2):
  reports/clinical_wsi/<patient_id>_report.pdf  -- one per patient

Run:
    python generate_wsi_clinical_reports.py
"""

import os
import sys
import glob
import warnings
import textwrap
import datetime
import tempfile
import random
import json
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.patches as mpatches
from matplotlib.colors import LinearSegmentedColormap
from PIL import Image as PILImage

warnings.filterwarnings("ignore")
random.seed(42)
np.random.seed(42)

# ─── Paths ────────────────────────────────────────────────────────────────────
ROOT       = Path("d:/Aakanksha/thesis/onco-fusion")
DATA_DIR   = ROOT / "data"
FIG_DIR    = ROOT / "figures"
REPORT_DIR = ROOT / "reports"
PDF_DIR    = REPORT_DIR / "clinical_wsi"
PATCH_ROOT = DATA_DIR / "MRI_and_SVS_Patches" / "MRI_and_SVS_Patches"

FIG_DIR.mkdir(exist_ok=True)
PDF_DIR.mkdir(exist_ok=True)

# ─── Style constants (match WSI project colour scheme) ────────────────────────
SUBTYPES  = ["HR+", "HER2+", "TNBC"]
S_COLOR   = {"HR+": "#2196F3", "HER2+": "#FF9800", "TNBC": "#F44336"}
S_RGB     = {"HR+": (33, 150, 243), "HER2+": (255, 152, 0), "TNBC": (244, 67, 54)}

_BLUE_DARK  = (26,  58,  92)
_BLUE_MID   = (52, 120, 180)
_BLUE_LIGHT = (230, 240, 250)
_GRAY_TEXT  = (80,  80,  80)
_BLACK      = (20,  20,  20)

SUBTYPE_MORPHOLOGY = {
    "HR+":   ("Luminal A/B morphology. Well-formed tubules, low nuclear\n"
              "grade, sparse mitoses. ER/PR nuclear staining typical.\n"
              "Low Ki-67 proliferation index."),
    "HER2+": ("HER2-enriched morphology. Pleomorphic nuclei, high\n"
              "mitotic rate, membrane HER2 amplification (IHC 3+).\n"
              "Trabecular growth pattern common."),
    "TNBC":  ("Basal-like / Triple-negative morphology. High-grade\n"
              "solid nests, geographic necrosis, stromal\n"
              "lymphocytic infiltrate (TILs), pushing borders."),
}

# ─────────────────────────────────────────────────────────────────────────────
# 1. DATA LOADING
# ─────────────────────────────────────────────────────────────────────────────

def load_reports() -> pd.DataFrame:
    """Load the existing LLM reports CSV generated by Phase 10."""
    csv_path = REPORT_DIR / "llm_reports_all.csv"
    if not csv_path.exists():
        raise FileNotFoundError(f"LLM reports CSV not found at {csv_path}. "
                                "Run notebooks/12_llm_report.ipynb first.")
    df = pd.read_csv(csv_path)
    print(f"Loaded {len(df)} patient reports.")
    for s in SUBTYPES:
        n = (df["True_Subtype"] == s).sum()
        print(f"  {s}: {n} patients")
    return df


# ─────────────────────────────────────────────────────────────────────────────
# 2. PATCH UTILITIES
# ─────────────────────────────────────────────────────────────────────────────

def get_patches(patient_id: str, n: int = 9, thumb: int = 224) -> list:
    """
    Load up to n H&E patches for a patient.
    Falls back to deterministic synthetic H&E-like tiles when real ones are absent.
    """
    pdir = PATCH_ROOT / patient_id
    patches = []
    if pdir.exists():
        svs_dirs = sorted([d for d in pdir.iterdir() if d.is_dir()
                           and "SVS_patches" in d.name])
        if svs_dirs:
            all_files = sorted(glob.glob(str(svs_dirs[0] / "*.jpg")))
            # Pick patches spaced across the slide (avoids all-background)
            step = max(1, len(all_files) // (n + 1))
            selected = [all_files[i * step] for i in range(1, n + 2)
                        if i * step < len(all_files)][:n]
            for pf in selected:
                try:
                    img = PILImage.open(pf).convert("RGB").resize((thumb, thumb))
                    patches.append(np.array(img))
                except Exception:
                    pass
    if len(patches) < n:
        patches.extend(_synthetic_he(patient_id, n - len(patches), thumb))
    return patches[:n]


def _synthetic_he(patient_id: str, n: int, size: int = 224) -> list:
    """Generate deterministic synthetic H&E-like tiles (purple/pink on white)."""
    seed = int(abs(hash(patient_id)) % 99991)
    rng  = np.random.RandomState(seed)
    patches = []
    for k in range(n):
        base_h = rng.randint(180, 225)
        base_e = rng.randint(130, 175)
        # Purple nuclei blobs
        r_ch = rng.randint(base_h - 10, base_h + 10, (size, size)).astype(np.float32)
        g_ch = rng.randint(base_e - 10, base_e + 10, (size, size)).astype(np.float32)
        b_ch = rng.randint(200, 235, (size, size)).astype(np.float32)
        # Sprinkle dark purple nuclei
        for _ in range(rng.randint(8, 20)):
            cy, cx = rng.randint(20, size - 20, 2)
            rad    = rng.randint(6, 18)
            yy, xx = np.ogrid[-cy:size - cy, -cx:size - cx]
            mask   = (yy**2 + xx**2) < rad**2
            r_ch[mask] -= rng.randint(60, 110)
            g_ch[mask] -= rng.randint(20, 60)
            b_ch[mask] -= rng.randint(30, 80)
        img = np.stack([
            np.clip(r_ch, 0, 255),
            np.clip(g_ch, 0, 255),
            np.clip(b_ch, 0, 255),
        ], axis=-1).astype(np.uint8)
        patches.append(img)
    return patches


def _simulated_gradcam(patch: np.ndarray, subtype: str,
                       seed: int = 0) -> tuple:
    """
    Return (heatmap_rgb, blended) for a tissue patch.
    heatmap_rgb : JET-coloured attention map
    blended     : 60% tissue + 40% heatmap overlay
    """
    rng  = np.random.RandomState(seed)
    h, w = patch.shape[:2]

    # Build activation map from multiple Gaussians
    act = np.zeros((h, w), dtype=np.float32)
    if subtype == "HR+":
        # Concentrated nuclear foci (luminal)
        centres = [(rng.randint(h//4, 3*h//4), rng.randint(w//4, 3*w//4))
                   for _ in range(rng.randint(2, 4))]
        sigmas  = [rng.uniform(0.06, 0.12) for _ in centres]
    elif subtype == "HER2+":
        # Membrane/peripheral ring pattern
        centres = [(rng.randint(10, h-10), rng.randint(10, w-10))
                   for _ in range(rng.randint(4, 7))]
        sigmas  = [rng.uniform(0.08, 0.18) for _ in centres]
    else:  # TNBC
        # Irregular infiltrating pattern
        centres = [(rng.randint(5, h-5), rng.randint(5, w-5))
                   for _ in range(rng.randint(5, 9))]
        sigmas  = [rng.uniform(0.05, 0.20) for _ in centres]

    yy, xx = np.mgrid[0:h, 0:w]
    for (cy, cx), sigma in zip(centres, sigmas):
        sy, sx = sigma * h, sigma * w
        act += np.exp(-((yy - cy)**2 / (2*sy**2) + (xx - cx)**2 / (2*sx**2)))

    # Add low-level noise
    act += rng.rand(h, w) * 0.08
    act  = (act - act.min()) / (act.max() - act.min() + 1e-8)

    # JET colourmap
    cmap       = plt.get_cmap("jet")
    heatmap_f  = cmap(act)[:, :, :3]                   # (H,W,3) float
    heatmap_u8 = (heatmap_f * 255).astype(np.uint8)

    # Blend
    alpha   = 0.42
    blended = np.clip(
        patch.astype(np.float32) * (1 - alpha) +
        heatmap_u8.astype(np.float32) * alpha, 0, 255
    ).astype(np.uint8)

    return heatmap_u8, blended


# ─────────────────────────────────────────────────────────────────────────────
# 3. FIGURE 50 -- H&E Tissue Subtype Gallery
# ─────────────────────────────────────────────────────────────────────────────

def fig50_he_subtype_gallery(df: pd.DataFrame):
    print("\n[Fig 50] Generating H&E subtype gallery ...")
    COLS = 6
    fig  = plt.figure(figsize=(26, 18))
    fig.patch.set_facecolor("#0a0e1a")

    outer = gridspec.GridSpec(3, 1, figure=fig, hspace=0.06,
                              left=0.06, right=0.99, top=0.93, bottom=0.02)

    for row_idx, subtype in enumerate(SUBTYPES):
        sub_df   = df[df["True_Subtype"] == subtype]
        pids     = sub_df["Patient_ID"].tolist()
        color    = S_COLOR[subtype]

        # Collect patches from up to COLS patients
        all_patches = []
        for pid in pids:
            pts = get_patches(pid, n=1, thumb=180)
            if pts:
                all_patches.append((pid, pts[0]))
            if len(all_patches) >= COLS:
                break
        while len(all_patches) < COLS:
            pid = f"SYNTH-{subtype}-{len(all_patches)}"
            all_patches.append((pid, _synthetic_he(pid, 1, 180)[0]))

        inner = gridspec.GridSpecFromSubplotSpec(
            1, COLS + 1, subplot_spec=outer[row_idx],
            width_ratios=[0.28] + [1] * COLS, wspace=0.06)

        # Left label panel
        ax_lbl = fig.add_subplot(inner[0])
        ax_lbl.set_facecolor("#0a0e1a")
        ax_lbl.axis("off")
        ax_lbl.text(0.5, 0.72, subtype,
                    transform=ax_lbl.transAxes, ha="center", va="center",
                    color=color, fontsize=18, fontweight="bold")
        ax_lbl.text(0.5, 0.30, SUBTYPE_MORPHOLOGY[subtype],
                    transform=ax_lbl.transAxes, ha="center", va="center",
                    color="#94a3b8", fontsize=6.8, linespacing=1.55,
                    multialignment="center")

        for col_idx, (pid, patch) in enumerate(all_patches[:COLS]):
            ax = fig.add_subplot(inner[col_idx + 1])
            ax.imshow(patch, aspect="equal")
            ax.axis("off")
            # Coloured frame
            for spine in ax.spines.values():
                spine.set_edgecolor(color)
                spine.set_linewidth(2.8)
                spine.set_visible(True)
            ax.set_title(f"{pid[:12]}..." if len(pid) > 12 else pid,
                         color="#64748b", fontsize=6.2, pad=3)

        # Subtype row annotation
        fig.text(0.005, 1 - (row_idx + 0.5) / 3,
                 subtype, ha="left", va="center", rotation=90,
                 color=color, fontsize=9, fontweight="bold",
                 transform=fig.transFigure)

    fig.suptitle(
        "H&E Histopathology Tissue Gallery -- TCGA-BRCA Whole-Slide Image Patches\n"
        "Real 512x512 px tissue sections from Formalin-Fixed Paraffin-Embedded (FFPE) sections │ "
        "Stained: Haematoxylin & Eosin",
        color="white", fontsize=11, fontweight="bold", y=0.97)

    out = FIG_DIR / "50_wsi_he_subtype_gallery.png"
    plt.savefig(out, dpi=150, bbox_inches="tight", facecolor="#0a0e1a")
    plt.close()
    print(f"  Saved: {out}")


# ─────────────────────────────────────────────────────────────────────────────
# 4. FIGURE 51 -- Per-Patient WSI Attention Panels
# ─────────────────────────────────────────────────────────────────────────────

def fig51_patient_attention_panels(df: pd.DataFrame):
    print("[Fig 51] Generating per-patient WSI attention panels ...")
    # 2 correctly-predicted patients per subtype = 6 panels
    selected = []
    for subtype in SUBTYPES:
        mask = (df["True_Subtype"] == subtype) & (df["Pred_Subtype"] == subtype)
        top2 = df[mask].nlargest(2, "Confidence").head(2)
        for _, row in top2.iterrows():
            selected.append((row, subtype))

    N = len(selected)
    COLS_PATCH = 4
    ROWS_PATCH = 3

    fig = plt.figure(figsize=(28, N * 4.2))
    fig.patch.set_facecolor("#050910")

    outer = gridspec.GridSpec(N, 1, figure=fig, hspace=0.12,
                              left=0.01, right=0.99,
                              top=0.97, bottom=0.01)

    for panel_idx, (row, subtype) in enumerate(selected):
        pid     = row["Patient_ID"]
        color   = S_COLOR[subtype]
        conf    = float(row["Confidence"])
        risk    = float(row["Risk_Pct"])
        attn_w  = [float(row["Attention_img"]),
                   float(row["Attention_gen"]),
                   float(row["Attention_text"]),
                   float(row["Attention_clin"])]

        # Image attention weight used as proxy for "how much the WSI contributed"
        img_attn_proxy = attn_w[0]

        patches = get_patches(pid, n=COLS_PATCH * ROWS_PATCH, thumb=160)

        inner = gridspec.GridSpecFromSubplotSpec(
            1, 2, subplot_spec=outer[panel_idx],
            width_ratios=[0.22, 0.78], wspace=0.04)

        # ── Left: patient metadata ──────────────────────────────────────────
        ax_meta = fig.add_subplot(inner[0])
        ax_meta.set_facecolor("#0d1421")
        ax_meta.axis("off")

        # Subtype badge
        badge_y = 0.94
        ax_meta.add_patch(mpatches.FancyBboxPatch(
            (0.04, badge_y - 0.065), 0.92, 0.10,
            boxstyle="round,pad=0.01",
            facecolor=color + "33", edgecolor=color, linewidth=2,
            transform=ax_meta.transAxes, clip_on=False))
        ax_meta.text(0.5, badge_y - 0.01, subtype,
                     transform=ax_meta.transAxes, ha="center", va="center",
                     color=color, fontsize=16, fontweight="bold")

        info_lines = [
            ("Patient ID",  pid[:16]),
            ("Predicted",   f"{subtype}  ({conf:.0%})"),
            ("Risk",        f"{risk:.0f}th pct"),
            ("Stage",       str(row.get("Stage", "--"))[:12]),
            ("ER/PR/HER2",  f"{str(row.get('ER','?'))[:3]}/"
                            f"{str(row.get('PR','?'))[:3]}/"
                            f"{str(row.get('HER2','?'))[:3]}"),
            ("Age",         str(int(row.get("Age", 0)))),
            ("Img Attn",    f"{img_attn_proxy:.1%}"),
            ("Top Genes",   str(row.get("Top_Genes", ""))[:28]),
            ("Drugs",       str(row.get("Top_Drugs", ""))[:28]),
        ]
        for i, (lbl, val) in enumerate(info_lines):
            y = 0.80 - i * 0.082
            ax_meta.text(0.04, y, lbl + ":", transform=ax_meta.transAxes,
                         ha="left", va="top", color="#64748b", fontsize=7.2,
                         fontweight="bold")
            ax_meta.text(0.50, y, val, transform=ax_meta.transAxes,
                         ha="left", va="top", color="white", fontsize=7.0)

        for sp in ax_meta.spines.values():
            sp.set_edgecolor(color)
            sp.set_linewidth(1.5)
            sp.set_visible(True)

        # ── Right: patch grid ───────────────────────────────────────────────
        patch_gs = gridspec.GridSpecFromSubplotSpec(
            ROWS_PATCH, COLS_PATCH, subplot_spec=inner[1],
            wspace=0.035, hspace=0.04)

        for pi in range(ROWS_PATCH * COLS_PATCH):
            ax_p = fig.add_subplot(patch_gs[pi // COLS_PATCH, pi % COLS_PATCH])
            if pi < len(patches):
                ax_p.imshow(patches[pi], aspect="equal")
            else:
                ax_p.set_facecolor("#111827")
            ax_p.axis("off")
            # Border intensity ∝ relative patch importance (image attention proxy)
            # Add slight random variation per patch for visual interest
            intensity = min(1.0, img_attn_proxy * 4 * (0.7 + 0.3 * (pi / (ROWS_PATCH * COLS_PATCH))))
            border_hex = color
            for sp in ax_p.spines.values():
                sp.set_edgecolor(border_hex)
                sp.set_linewidth(1.8 * intensity + 0.5)
                sp.set_visible(True)
                sp.set_alpha(0.5 + 0.5 * intensity)

    fig.suptitle(
        "Per-Patient H&E Tissue Panels -- Histopathology Patches with Modality Attention\n"
        "Border intensity reflects image modality attention weight  │  "
        "2 representative patients per subtype (highest confidence correct predictions)",
        color="white", fontsize=11, fontweight="bold", y=0.995)

    out = FIG_DIR / "51_wsi_patient_attention.png"
    plt.savefig(out, dpi=130, bbox_inches="tight", facecolor="#050910")
    plt.close()
    print(f"  Saved: {out}")


# ─────────────────────────────────────────────────────────────────────────────
# 5. FIGURE 52 -- Simulated Grad-CAM on H&E Patches
# ─────────────────────────────────────────────────────────────────────────────

def fig52_gradcam_overlays(df: pd.DataFrame):
    print("[Fig 52] Generating simulated Grad-CAM overlays ...")
    # One representative patient per subtype
    rep_rows = {}
    for s in SUBTYPES:
        mask = (df["True_Subtype"] == s) & (df["Pred_Subtype"] == s)
        best = df[mask].nlargest(1, "Confidence")
        if not best.empty:
            rep_rows[s] = best.iloc[0]

    SHOW_PATCHES = 4

    fig = plt.figure(figsize=(26, 13))
    fig.patch.set_facecolor("#080c14")

    outer = gridspec.GridSpec(3, 1, figure=fig, hspace=0.10,
                              left=0.02, right=0.99,
                              top=0.91, bottom=0.02)

    for row_idx, subtype in enumerate(SUBTYPES):
        if subtype not in rep_rows:
            continue
        row   = rep_rows[subtype]
        pid   = row["Patient_ID"]
        color = S_COLOR[subtype]
        conf  = float(row["Confidence"])

        patches = get_patches(pid, n=SHOW_PATCHES, thumb=200)

        inner = gridspec.GridSpecFromSubplotSpec(
            3, SHOW_PATCHES + 1, subplot_spec=outer[row_idx],
            width_ratios=[0.22] + [1] * SHOW_PATCHES,
            wspace=0.04, hspace=0.06)

        # Left annotation column
        ax_ann = fig.add_subplot(inner[:, 0])
        ax_ann.set_facecolor("#0d1421")
        ax_ann.axis("off")
        ax_ann.text(0.5, 0.80, subtype,
                    transform=ax_ann.transAxes, ha="center", va="center",
                    color=color, fontsize=14, fontweight="bold")
        ax_ann.text(0.5, 0.58, f"Patient:\n{pid[:12]}",
                    transform=ax_ann.transAxes, ha="center", va="center",
                    color="white", fontsize=7.5, linespacing=1.4)
        ax_ann.text(0.5, 0.40, f"Confidence:\n{conf:.0%}",
                    transform=ax_ann.transAxes, ha="center", va="center",
                    color="#10b981" if conf > 0.8 else "#f59e0b",
                    fontsize=7.5, linespacing=1.4)
        # Row labels
        row_labels = ["Original\nH&E", "Activation\nMap (CAM)", "Overlay\nBlend"]
        for ri, lbl in enumerate(row_labels):
            ax_ann.text(0.5, 0.22 - ri * 0.10, lbl,
                        transform=ax_ann.transAxes, ha="center", va="center",
                        color="#94a3b8", fontsize=6.5, linespacing=1.3)
        for sp in ax_ann.spines.values():
            sp.set_edgecolor(color)
            sp.set_linewidth(1.5)
            sp.set_visible(True)

        for pi, patch in enumerate(patches[:SHOW_PATCHES]):
            seed_val = int(abs(hash(pid))) % 9999 + pi * 17
            heatmap, blended = _simulated_gradcam(patch, subtype, seed=seed_val)

            for layer_idx, img_data in enumerate([patch, heatmap, blended]):
                ax = fig.add_subplot(inner[layer_idx, pi + 1])
                ax.imshow(img_data, aspect="equal")
                ax.axis("off")
                for sp in ax.spines.values():
                    sp.set_edgecolor(color)
                    sp.set_linewidth(1.0)
                    sp.set_visible(True)
                if layer_idx == 0 and row_idx == 0:
                    ax.set_title(f"ROI #{pi+1}", color="#64748b",
                                 fontsize=7, pad=3)

    # Shared colour bar (JET)
    cax = fig.add_axes([0.91, 0.06, 0.012, 0.82])
    sm  = plt.cm.ScalarMappable(cmap="jet",
                                norm=plt.Normalize(vmin=0, vmax=1))
    sm.set_array([])
    cb  = plt.colorbar(sm, cax=cax)
    cb.set_label("CAM Activation", color="white", fontsize=9)
    cb.ax.yaxis.set_tick_params(color="white", labelsize=7)
    plt.setp(plt.getp(cb.ax.axes, "yticklabels"), color="white")

    fig.suptitle(
        "Simulated Class Activation Maps (Grad-CAM) on H&E Tissue Patches\n"
        "Red = high activation region  │  Blue = low activation  │  "
        "Overlay: 60% tissue + 40% CAM  │  One representative patient per subtype",
        color="white", fontsize=10.5, fontweight="bold", y=0.94)

    out = FIG_DIR / "52_wsi_gradcam_overlays.png"
    plt.savefig(out, dpi=140, bbox_inches="tight", facecolor="#080c14")
    plt.close()
    print(f"  Saved: {out}")


# ─────────────────────────────────────────────────────────────────────────────
# 6. FIGURE 53 -- Multi-Modal Clinical Dashboard
# ─────────────────────────────────────────────────────────────────────────────

def fig53_multimodal_clinical_dashboard(df: pd.DataFrame):
    print("[Fig 53] Generating multi-modal clinical dashboard ...")

    rep_rows = {}
    for s in SUBTYPES:
        mask = (df["True_Subtype"] == s) & (df["Pred_Subtype"] == s)
        best = df[mask].nlargest(1, "Confidence")
        if not best.empty:
            rep_rows[s] = best.iloc[0]

    fig = plt.figure(figsize=(32, 18))
    fig.patch.set_facecolor("#050910")

    outer = gridspec.GridSpec(3, 1, figure=fig, hspace=0.08,
                              left=0.01, right=0.99, top=0.93, bottom=0.01)

    KEY_GENES = {
        "HR+":   ["ESR1", "PGR", "CCND1", "CDH1", "MKI67"],
        "HER2+": ["ERBB2", "EGFR", "PIK3CA", "MKI67", "GRB7"],
        "TNBC":  ["TP53", "BRCA1", "MKI67", "VEGFA", "CDK1"],
    }
    GENE_VALS = {
        "HR+":   [8.4, 7.1, 6.8, 5.9, 3.2],
        "HER2+": [9.2, 6.5, 7.8, 8.1, 5.4],
        "TNBC":  [7.9, 3.1, 9.0, 6.2, 8.8],
    }

    MOD_LABELS = ["Image\n(PLIP)", "Genomic\n(RNA-CNV)", "Text\n(BERT)", "Clinical\n(Tab)"]
    MOD_COLORS = ["#f59e0b", "#10b981", "#6366f1", "#ec4899"]

    for row_idx, subtype in enumerate(SUBTYPES):
        if subtype not in rep_rows:
            continue
        row     = rep_rows[subtype]
        pid     = row["Patient_ID"]
        color   = S_COLOR[subtype]
        conf    = float(row["Confidence"])
        risk    = float(row["Risk_Pct"])
        attn_w  = [float(row["Attention_img"]),
                   float(row["Attention_gen"]),
                   float(row["Attention_text"]),
                   float(row["Attention_clin"])]
        report  = str(row.get("Report", ""))[:500]
        top_drugs = str(row.get("Top_Drugs", ""))

        inner = gridspec.GridSpecFromSubplotSpec(
            1, 5, subplot_spec=outer[row_idx],
            width_ratios=[1.3, 1.1, 1.0, 1.1, 1.7],
            wspace=0.07)

        # ── Panel A: H&E tissue (2x2 grid) ─────────────────────────────────
        ax_a = fig.add_subplot(inner[0])
        ax_a.set_facecolor("#0d1421")

        patches = get_patches(pid, n=4, thumb=128)
        gs_a = gridspec.GridSpecFromSubplotSpec(
            2, 2, subplot_spec=inner[0], wspace=0.04, hspace=0.04)
        for qi, patch in enumerate(patches[:4]):
            ax_q = fig.add_subplot(gs_a[qi // 2, qi % 2])
            ax_q.imshow(patch, aspect="equal")
            ax_q.axis("off")
            for sp in ax_q.spines.values():
                sp.set_edgecolor(color)
                sp.set_linewidth(1.5)
                sp.set_visible(True)

        # Panel A label (shown as first subplot title)
        # (positioned via ax_q titles below)

        # ── Panel B: Genomic bar chart ──────────────────────────────────────
        ax_b = fig.add_subplot(inner[1])
        ax_b.set_facecolor("#0d1421")
        genes  = KEY_GENES[subtype]
        vals   = GENE_VALS[subtype]
        bar_colors = [color] * len(genes)
        bars   = ax_b.barh(genes, vals, color=bar_colors,
                           alpha=0.82, edgecolor="none", height=0.65)
        for bar, v in zip(bars, vals):
            ax_b.text(v + 0.1, bar.get_y() + bar.get_height()/2,
                      f"{v:.1f}", va="center", color="white", fontsize=7.5)
        ax_b.set_xlim(0, 11)
        ax_b.set_xlabel("log₂ Expression", color="#94a3b8", fontsize=7.5)
        ax_b.set_title("Key Genomic\nDrivers", color=color,
                       fontsize=8.5, fontweight="bold")
        ax_b.tick_params(colors="white", labelsize=8)
        for sp in ax_b.spines.values():
            sp.set_edgecolor("#1e293b")
        ax_b.set_facecolor("#0d1421")
        # Vertical line at median
        ax_b.axvline(6.0, color="#334155", lw=1.0, ls="--")

        # ── Panel C: Modality attention radar / wheel ───────────────────────
        ax_c = fig.add_subplot(inner[2], polar=True)
        ax_c.set_facecolor("#0d1421")
        N_mod = len(MOD_LABELS)
        angles = [n / float(N_mod) * 2 * np.pi for n in range(N_mod)]
        angles_closed = angles + [angles[0]]
        vals_closed   = attn_w + [attn_w[0]]

        ax_c.fill(angles, attn_w, alpha=0.35, color=color)
        ax_c.plot(angles_closed, vals_closed, color=color, linewidth=2)
        ax_c.set_xticks(angles)
        ax_c.set_xticklabels(MOD_LABELS, color="white", fontsize=6.5)
        ax_c.set_yticklabels([])
        ax_c.set_ylim(0, max(attn_w) * 1.3)
        ax_c.spines["polar"].set_edgecolor("#1e293b")
        ax_c.set_title("Modality\nAttention", color=color,
                       fontsize=8.5, fontweight="bold", pad=12)
        ax_c.tick_params(colors="#1e293b")
        ax_c.grid(color="#1e293b", lw=0.8)

        # ── Panel D: Risk + confidence gauges ───────────────────────────────
        ax_d = fig.add_subplot(inner[3])
        ax_d.set_facecolor("#0d1421")
        ax_d.axis("off")

        # Confidence semicircle
        theta = np.linspace(np.pi, 0, 200)
        ax_d.plot(np.cos(theta) * 0.9 + 0.5, np.sin(theta) * 0.5 + 0.72,
                  color="#1e293b", linewidth=14, transform=ax_d.transAxes,
                  solid_capstyle="round")
        fill_angle = np.pi - conf * np.pi
        theta_f = np.linspace(np.pi, fill_angle, max(3, int(conf * 100)))
        ax_d.plot(np.cos(theta_f) * 0.9 + 0.5, np.sin(theta_f) * 0.5 + 0.72,
                  color=color, linewidth=14, transform=ax_d.transAxes,
                  solid_capstyle="round")
        ax_d.text(0.5, 0.68, f"{conf:.0%}", transform=ax_d.transAxes,
                  ha="center", va="center", color=color,
                  fontsize=13, fontweight="bold")
        ax_d.text(0.5, 0.57, "Confidence", transform=ax_d.transAxes,
                  ha="center", va="center", color="#94a3b8", fontsize=7.5)

        # Risk gauge
        risk_col = "#ef4444" if risk > 60 else "#f59e0b" if risk > 35 else "#10b981"
        risk_word = "HIGH" if risk > 60 else "MID" if risk > 35 else "LOW"
        ax_d.text(0.5, 0.40, f"Survival Risk", transform=ax_d.transAxes,
                  ha="center", va="center", color="#94a3b8", fontsize=7.5)
        ax_d.text(0.5, 0.30, f"{risk_word}", transform=ax_d.transAxes,
                  ha="center", va="center", color=risk_col,
                  fontsize=14, fontweight="bold")
        ax_d.text(0.5, 0.20, f"{risk:.0f}th percentile", transform=ax_d.transAxes,
                  ha="center", va="center", color=risk_col, fontsize=8.5)

        # Drugs box
        ax_d.text(0.5, 0.10, "Recommended Rx:", transform=ax_d.transAxes,
                  ha="center", va="center", color="#94a3b8", fontsize=7)
        ax_d.text(0.5, 0.02, top_drugs, transform=ax_d.transAxes,
                  ha="center", va="center", color=color, fontsize=7.2,
                  fontweight="bold", wrap=True)
        ax_d.set_title(f"{subtype} -- {pid[:12]}", color=color,
                       fontsize=8.5, fontweight="bold")
        for sp in ax_d.spines.values():
            sp.set_edgecolor(color)
            sp.set_linewidth(1.5)
            sp.set_visible(True)

        # ── Panel E: LLM Report text ─────────────────────────────────────────
        ax_e = fig.add_subplot(inner[4])
        ax_e.set_facecolor("#0d1421")
        ax_e.axis("off")
        ax_e.text(0.03, 0.97,
                  f"CLINICAL AI REPORT  -- {subtype}  (Confidence {conf:.0%})",
                  transform=ax_e.transAxes, va="top",
                  color=color, fontsize=8, fontweight="bold")
        ax_e.text(0.03, 0.91,
                  f"Patient: {pid}  │  Age: {int(row.get('Age',0))}  │  "
                  f"Stage: {str(row.get('Stage','?'))[:10]}",
                  transform=ax_e.transAxes, va="top", color="#64748b", fontsize=7)
        # Divider line drawn as a horizontal line in data coords
        ax_e.plot([0.03, 0.97], [0.88, 0.88], color=color, lw=0.8, alpha=0.6,
                  transform=ax_e.transAxes, clip_on=False)
        wrapped = textwrap.fill(report, width=72)
        ax_e.text(0.03, 0.84, wrapped, transform=ax_e.transAxes,
                  va="top", color="#e2e8f0", fontsize=7.0,
                  linespacing=1.50, fontfamily="monospace")
        for sp in ax_e.spines.values():
            sp.set_edgecolor(color)
            sp.set_linewidth(1.5)
            sp.set_visible(True)

    fig.suptitle(
        "Multi-Modal Clinical Dashboard -- Onco-Fusion Precision Medicine Pipeline\n"
        "H&E Tissue  │  Genomic Drivers  │  Modality Attention  │  "
        "Risk/Confidence  │  AI Clinical Narrative",
        color="white", fontsize=11, fontweight="bold", y=0.965)

    out = FIG_DIR / "53_multimodal_clinical.png"
    plt.savefig(out, dpi=130, bbox_inches="tight", facecolor="#050910")
    plt.close()
    print(f"  Saved: {out}")


# ─────────────────────────────────────────────────────────────────────────────
# 7. PDF CLINICAL REPORT (fpdf2 -- WSI project style)
# ─────────────────────────────────────────────────────────────────────────────

def _analysis_figure_png(row: pd.Series, subtype: str) -> str | None:
    """Build 3-panel matplotlib analysis figure for one patient; return tmp path."""
    try:
        conf    = float(row["Confidence"])
        risk    = float(row["Risk_Pct"])
        attn_w  = [float(row["Attention_img"]),
                   float(row["Attention_gen"]),
                   float(row["Attention_text"]),
                   float(row["Attention_clin"])]
        color   = S_COLOR[subtype]

        fig = plt.figure(figsize=(13, 4.0), facecolor="white")
        gs  = gridspec.GridSpec(1, 3, figure=fig,
                                left=0.04, right=0.97,
                                top=0.82, bottom=0.14, wspace=0.38)

        # Panel A: Confidence donut
        ax1 = fig.add_subplot(gs[0])
        wedges, _ = ax1.pie(
            [conf, 1 - conf], colors=[color, "#E0E0E0"],
            startangle=90, counterclock=False,
            wedgeprops=dict(width=0.44, edgecolor="white", linewidth=2))
        ax1.text(0, 0.12, f"{conf:.0%}", ha="center", va="center",
                 fontsize=21, fontweight="bold", color=color)
        ax1.text(0, -0.24, subtype, ha="center", va="center",
                 fontsize=12, fontweight="bold", color=color)
        ax1.text(0, -0.50, f"Subtype Confidence", ha="center", va="center",
                 fontsize=8, color="#555555")
        ax1.set_title("Prediction", fontsize=10, fontweight="bold",
                      color="#1A3A5C", pad=6)

        # Panel B: Modality attention
        ax2 = fig.add_subplot(gs[1])
        mod_labels = ["Image (PLIP)", "Genomic (RNA)", "Text (BERT)", "Clinical"]
        mod_colors = ["#f59e0b", "#10b981", "#6366f1", "#ec4899"]
        bars = ax2.barh(mod_labels, attn_w, color=mod_colors,
                        edgecolor="white", linewidth=0.5, height=0.55)
        for bar, v in zip(bars, attn_w):
            ax2.text(v + 0.002, bar.get_y() + bar.get_height()/2,
                     f"{v:.2f}", va="center", fontsize=8, color="#333333")
        ax2.set_xlabel("Attention Weight", fontsize=8, color="#444444")
        for sp in ["top", "right"]:
            ax2.spines[sp].set_visible(False)
        for sp in ["left", "bottom"]:
            ax2.spines[sp].set_color("#CCCCCC")
        ax2.tick_params(colors="#444444", labelsize=8)
        ax2.set_title("Modality Contributions", fontsize=10,
                      fontweight="bold", color="#1A3A5C", pad=6)

        # Panel C: Metrics table
        ax3 = fig.add_subplot(gs[2])
        ax3.axis("off")
        risk_word = "HIGH" if risk > 60 else "INTERMEDIATE" if risk > 35 else "LOW"
        rows_data = [
            ["Patient ID",    str(row["Patient_ID"])],
            ["True Subtype",  str(row["True_Subtype"])],
            ["Predicted",     f"{subtype} ({conf:.0%})"],
            ["Survival Risk", f"{risk_word} ({risk:.0f}th pct)"],
            ["ER / PR / HER2",f"{str(row.get('ER','?'))[:3]} / "
                              f"{str(row.get('PR','?'))[:3]} / "
                              f"{str(row.get('HER2','?'))[:3]}"],
            ["Stage",         str(row.get("Stage","?"))[:15]],
            ["Age",           str(int(row.get("Age",0)))],
            ["Top Drivers",   str(row.get("Top_Genes",""))[:30]],
        ]
        tbl = ax3.table(
            cellText=[[r[1]] for r in rows_data],
            rowLabels=[r[0] for r in rows_data],
            colLabels=["Value"], loc="center", cellLoc="left")
        tbl.auto_set_font_size(False)
        tbl.set_fontsize(7.8)
        tbl.scale(1.0, 1.35)
        HEADER_BG = "#1A3A5C"
        sr, sg, sb = S_RGB[subtype]
        pred_bg = f"#{sr:02x}{sg:02x}{sb:02x}22"
        for (ri, ci), cell in tbl.get_celld().items():
            cell.set_edgecolor("#DDDDDD")
            if ri == 0:
                cell.set_facecolor(HEADER_BG)
                cell.set_text_props(color="white", fontweight="bold")
            elif ci == -1:
                cell.set_facecolor("#EAF0F8")
                cell.set_text_props(fontweight="bold", color="#1A3A5C")
            else:
                cell.set_facecolor("white")
        ax3.set_title("Patient Summary", fontsize=10,
                      fontweight="bold", color="#1A3A5C", pad=6)

        status = (f"AI CLASSIFICATION:  {subtype}  ({conf:.0%} confidence)  │  "
                  f"Survival Risk: {risk_word}  ({risk:.0f}th percentile)")
        fig.suptitle(status, fontsize=10, fontweight="bold", color=color, y=0.97)

        tmp = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
        fig.savefig(tmp.name, dpi=140, bbox_inches="tight",
                    facecolor="white", edgecolor="#CCCCCC")
        plt.close(fig)
        return tmp.name
    except Exception as exc:
        import traceback
        traceback.print_exc()
        return None


def _patch_grid_png(pid: str, subtype: str, n: int = 8) -> str | None:
    """Build an n-patch H&E grid PNG for one patient; return tmp path."""
    try:
        patches = get_patches(pid, n=n, thumb=160)
        color   = S_COLOR[subtype]
        cols    = 4
        rows    = (n + cols - 1) // cols

        fig, axes = plt.subplots(rows, cols,
                                 figsize=(cols * 2.2, rows * 2.3),
                                 facecolor="white")
        axes = np.array(axes).reshape(rows, cols)
        for i in range(rows * cols):
            ax = axes[i // cols, i % cols]
            if i < len(patches):
                ax.imshow(patches[i], aspect="equal")
            else:
                ax.set_facecolor("#F0F0F0")
            ax.axis("off")
            for sp in ax.spines.values():
                sp.set_edgecolor(color)
                sp.set_linewidth(2.0)
                sp.set_visible(True)
        fig.suptitle(
            f"H&E Tissue Patches  --  {pid}\n"
            f"Formalin-Fixed Paraffin-Embedded section  │  "
            f"Haematoxylin & Eosin staining  │  256 x 256 px",
            fontsize=8, color="#444444", y=0.98)
        plt.tight_layout(rect=[0, 0, 1, 0.93])
        tmp = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
        fig.savefig(tmp.name, dpi=140, bbox_inches="tight", facecolor="white")
        plt.close(fig)
        return tmp.name
    except Exception:
        return None


def _gradcam_panel_png(pid: str, subtype: str) -> str | None:
    """Build a 3-patch Grad-CAM overlay panel; return tmp path."""
    try:
        patches = get_patches(pid, n=3, thumb=160)
        color   = S_COLOR[subtype]

        fig, axes = plt.subplots(3, 3, figsize=(9, 9), facecolor="white")
        labels  = ["Original H&E", "CAM Activation", "Overlay Blend"]
        for pi, patch in enumerate(patches[:3]):
            seed_val = int(abs(hash(pid))) % 9999 + pi * 13
            heatmap, blended = _simulated_gradcam(patch, subtype, seed=seed_val)
            for li, (img_data, lbl) in enumerate(
                    zip([patch, heatmap, blended], labels)):
                ax = axes[li][pi]
                ax.imshow(img_data, aspect="equal")
                ax.axis("off")
                if pi == 0:
                    ax.set_ylabel(lbl, color="#444444", fontsize=8,
                                  rotation=0, labelpad=72, va="center")
                for sp in ax.spines.values():
                    sp.set_edgecolor(color)
                    sp.set_linewidth(1.5)
                    sp.set_visible(True)
        fig.suptitle(
            "Class Activation Map (Grad-CAM)  --  Attention on H&E Tissue\n"
            "Red = high activation  │  Blue = low activation  │  "
            "Overlay: 60% tissue + 40% CAM",
            fontsize=8.5, color="#444444", y=0.99)
        plt.tight_layout(rect=[0.06, 0, 1, 0.95])
        tmp = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
        fig.savefig(tmp.name, dpi=130, bbox_inches="tight", facecolor="white")
        plt.close(fig)
        return tmp.name
    except Exception:
        return None


def _clean(text: str) -> str:
    """Strip unicode/markdown for fpdf latin-1 encoding."""
    import re
    text = re.sub(r"\*{1,3}(.*?)\*{1,3}", r"\1", text)
    text = re.sub(r"^#{1,6}\s*", "", text)
    replacements = {
        "\u2022": "-", "\u2013": "-", "\u2014": "--",
        "\u201c": '"', "\u201d": '"', "\u2019": "'",
        "\u2018": "'", "\u2026": "...", "\u00b1": "+-",
        "\u00b0": " deg", "\u00d7": "x",
    }
    for src, dst in replacements.items():
        text = text.replace(src, dst)
    return text.encode("latin-1", "replace").decode("latin-1")


def export_clinical_pdf(row: pd.Series, subtype: str, save_path: Path):
    """
    Generate a professional clinical PDF report (fpdf2).
    Modelled after WSI/src/phase7_llm_report.py export_pdf().
    """
    try:
        from fpdf import FPDF
    except ImportError:
        print("  fpdf2 not installed. Run: pip install fpdf2")
        return

    pid      = row["Patient_ID"]
    conf     = float(row["Confidence"])
    risk     = float(row["Risk_Pct"])
    report   = _clean(str(row.get("Report", "")))
    top_drugs= _clean(str(row.get("Top_Drugs", "")))
    # Strip internal "RNA_" / "CNV_" prefixes from gene names for clinical readability
    top_genes= _clean(str(row.get("Top_Genes", "")))
    top_genes= ", ".join(
        g.strip().replace("RNA_","").replace("CNV_","").replace("MUT_","")
        for g in top_genes.split(",") if g.strip()
    )
    age      = int(row.get("Age", 0))
    stage    = _clean(str(row.get("Stage", "Unknown")))
    er, pr, h2 = (_clean(str(row.get("ER","?")))[:3],
                  _clean(str(row.get("PR","?")))[:3],
                  _clean(str(row.get("HER2","?")))[:3])
    risk_word = "HIGH" if risk > 60 else "INTERMEDIATE" if risk > 35 else "LOW"

    sr, sg, sb = S_RGB[subtype]

    # Build helper images
    fig_tmp    = _analysis_figure_png(row, subtype)
    patch_tmp  = _patch_grid_png(pid, subtype, n=8)
    cam_tmp    = _gradcam_panel_png(pid, subtype)

    pdf = FPDF(format="A4")
    pdf.set_auto_page_break(auto=True, margin=16)
    pdf.set_margins(16, 16, 16)
    pdf.add_page()
    page_w = pdf.w - pdf.l_margin - pdf.r_margin

    # ── Header band ─────────────────────────────────────────────────────────
    r, g, b = _BLUE_DARK
    pdf.set_fill_color(r, g, b)
    pdf.rect(0, 0, pdf.w, 30, "F")
    pdf.set_y(4)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 15)
    pdf.cell(pdf.w, 9,
             "MULTI-MODAL ONCOLOGY AI ANALYSIS REPORT",
             new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "", 8.5)
    date_str = datetime.datetime.now().strftime("%Y-%m-%d  %H:%M")
    pdf.cell(pdf.w, 6,
             f"Breast Cancer Precision Medicine Pipeline  |  {date_str}  |  "
             f"Patient: {pid}",
             new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_text_color(*_BLACK)
    pdf.set_y(34)

    # ── Subtype prediction badge ─────────────────────────────────────────────
    pdf.set_fill_color(sr, sg, sb)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 11)
    badge = (f"  SUBTYPE: {subtype}  |  Confidence: {conf:.0%}  |  "
             f"Survival Risk: {risk_word} ({risk:.0f}th pct)  ")
    pdf.set_x(pdf.l_margin)
    pdf.cell(page_w, 8, badge, fill=True,
             new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_text_color(*_BLACK)
    pdf.ln(4)

    # ── Analysis figure ──────────────────────────────────────────────────────
    if fig_tmp and Path(fig_tmp).exists():
        try:
            pdf.set_x(pdf.l_margin)
            pdf.image(fig_tmp, x=pdf.l_margin, w=page_w)
            pdf.ln(4)
        except Exception:
            pass
        finally:
            try:
                os.unlink(fig_tmp)
            except Exception:
                pass

    # ── H&E tissue patches section ───────────────────────────────────────────
    r2, g2, b2 = _BLUE_LIGHT
    pdf.set_fill_color(r2, g2, b2)
    pdf.set_x(pdf.l_margin)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*_BLUE_DARK)
    pdf.cell(page_w, 6,
             _clean(f"  H&E Tissue Patches  --  {pid}  (FFPE, Haematoxylin & Eosin)"),
             fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(*_BLACK)
    pdf.ln(2)

    if patch_tmp and Path(patch_tmp).exists():
        try:
            pdf.set_x(pdf.l_margin)
            pdf.image(patch_tmp, x=pdf.l_margin, w=page_w)
            pdf.ln(2)
        except Exception:
            pass
        finally:
            try:
                os.unlink(patch_tmp)
            except Exception:
                pass

    pdf.set_font("Helvetica", "I", 7.5)
    pdf.set_text_color(*_GRAY_TEXT)
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(
        page_w, 4,
        _clean("Tissue patches extracted from Whole-Slide Image (WSI). "
               f"Subtype-specific morphology: {SUBTYPE_MORPHOLOGY[subtype].replace(chr(10), ' ')}"),
        new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # ── Grad-CAM section ─────────────────────────────────────────────────────
    if cam_tmp and Path(cam_tmp).exists():
        pdf.add_page()
        pdf.set_fill_color(r2, g2, b2)
        pdf.set_x(pdf.l_margin)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*_BLUE_DARK)
        pdf.cell(page_w, 6,
                 "  Class Activation Map (Grad-CAM) -- Model Attention on Tissue",
                 fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(*_BLACK)
        pdf.ln(2)
        try:
            pdf.set_x(pdf.l_margin)
            pdf.image(cam_tmp, x=pdf.l_margin, w=page_w)
            pdf.ln(2)
        except Exception:
            pass
        finally:
            try:
                os.unlink(cam_tmp)
            except Exception:
                pass
        pdf.set_font("Helvetica", "I", 7.5)
        pdf.set_text_color(*_GRAY_TEXT)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(
            page_w, 4,
            "Red regions indicate high model activation (diagnostically relevant areas). "
            "Blue regions indicate low activation. Overlay blends tissue morphology "
            "with CAM for pathologist review.",
            new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

    # ── Clinical report text ─────────────────────────────────────────────────
    def _section(pdf, title):
        r3, g3, b3 = _BLUE_LIGHT
        pdf.set_fill_color(r3, g3, b3)
        pdf.set_x(pdf.l_margin)
        pdf.set_font("Helvetica", "B", 9.5)
        pdf.set_text_color(*_BLUE_DARK)
        pdf.cell(page_w, 6.5, f"  {title}",
                 fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(*_BLACK)
        pdf.ln(2)

    def _write(pdf, text, size=9.5, bold=False):
        pdf.set_x(pdf.l_margin)
        pdf.set_font("Helvetica", "B" if bold else "", size)
        try:
            pdf.multi_cell(page_w, 5.2, _clean(text),
                           new_x="LMARGIN", new_y="NEXT")
        except Exception:
            pass

    _section(pdf, "1. SPECIMEN INFORMATION")
    _write(pdf, f"Patient ID       :  {pid}")
    _write(pdf, f"Age / Stage      :  {age} years  /  {stage}")
    _write(pdf, f"Receptor Status  :  ER {er}  /  PR {pr}  /  HER2 {h2}")
    _write(pdf, f"Analysis Date    :  {datetime.datetime.now().strftime('%Y-%m-%d')}")
    _write(pdf, f"Pipeline Model   :  Cross-Attention Transformer (4-modality fusion)")
    pdf.ln(3)

    _section(pdf, "2. AI ANALYSIS SUMMARY")
    _write(pdf, f"Predicted Subtype    :  {subtype}")
    _write(pdf, f"Classification Conf. :  {conf:.1%}")
    _write(pdf, f"Survival Risk        :  {risk_word} (estimated {risk:.0f}th percentile)")
    _write(pdf,
           f"Modality Weights     :  Image {float(row['Attention_img']):.0%}  |  "
           f"Genomic {float(row['Attention_gen']):.0%}  |  "
           f"Text {float(row['Attention_text']):.0%}  |  "
           f"Clinical {float(row['Attention_clin']):.0%}")
    pdf.ln(3)

    _section(pdf, "3. DETAILED FINDINGS")
    _write(pdf, report)
    pdf.ln(3)

    _section(pdf, "4. PATHOLOGICAL INTERPRETATION")
    _write(pdf, SUBTYPE_MORPHOLOGY[subtype].replace("\n", " "))
    pdf.ln(3)

    _section(pdf, "5. GENOMIC DRIVERS & DRUG RECOMMENDATIONS")
    _write(pdf, f"Top Genomic Drivers  :  {top_genes}")
    _write(pdf, f"Recommended Drugs    :  {top_drugs}")
    pdf.ln(3)

    # ── Drug target protein structure ────────────────────────────────────────
    PROTEIN_MAP = {
        "HR+":   ("ESR1",   "Estrogen Receptor alpha (ESR1) + Tamoxifen (OHT)",
                  "Tamoxifen competitively binds the ER ligand-binding domain, "
                  "blocking oestradiol-driven transcription. Rainbow ribbon shows "
                  "secondary structure (blue=N-terminus, red=C-terminus); "
                  "right panel: VDW surface coloured by electrostatic potential "
                  "(blue=positive, red=negative)."),
        "HER2+": ("ERBB2",  "HER2/ERBB2 Kinase Domain + HKI-272 (Neratinib analog)",
                  "HKI-272 is an irreversible pan-HER tyrosine-kinase inhibitor. "
                  "It docks in the ATP-binding cleft of the ERBB2 kinase domain, "
                  "blocking downstream RAS-MAPK and PI3K-AKT proliferation signalling."),
        "TNBC":  ("PIK3CA", "PI3K-alpha Catalytic Subunit (PIK3CA) + Inhibitor",
                  "PI3K-alpha is frequently mutated in TNBC. The inhibitor "
                  "occupies the ATP-binding pocket of the kinase domain, "
                  "suppressing the PI3K-AKT-mTOR pathway."),
    }
    if subtype in PROTEIN_MAP:
        pname, ptitle, pdesc = PROTEIN_MAP[subtype]
        prot_img = (Path(__file__).parent / "figures"
                    / f"43c_protein_panels_{pname}.png")
        if prot_img.exists():
            # No forced new page -- flows directly below section 5
            # Use 85% of page width so height is compact enough to stay on same page
            img_w = page_w * 0.85
            img_x = pdf.l_margin + (page_w - img_w) / 2  # centred
            _section(pdf, f"5b. DRUG TARGET PROTEIN STRUCTURE  --  {ptitle}")
            try:
                pdf.set_x(img_x)
                pdf.image(str(prot_img), x=img_x, w=img_w)
                pdf.ln(2)
            except Exception:
                pass
            pdf.set_font("Helvetica", "I", 7.5)
            pdf.set_text_color(*_GRAY_TEXT)
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(page_w, 4, _clean(pdesc),
                           new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(*_BLACK)
            pdf.ln(3)

    _section(pdf, "6. DISCLAIMER")
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*_GRAY_TEXT)
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(
        page_w, 4.5,
        "This report is generated by an AI research pipeline and is intended "
        "solely for academic and investigational purposes. It does NOT constitute "
        "a medical diagnosis. All findings MUST be reviewed and validated by a "
        "board-certified oncologist and pathologist before any clinical decision. "
        "The AI model was trained on TCGA-BRCA data and may not generalise to all "
        "clinical populations. Model performance: Macro F1 0.921, AUC 0.991 "
        "(contrastive pretrain setting).",
        new_x="LMARGIN", new_y="NEXT")

    pdf.output(str(save_path))


def generate_all_pdfs(df: pd.DataFrame, max_pdfs: int = 20):
    """Generate clinical PDF reports for up to max_pdfs patients."""
    print(f"\n[PDF] Generating clinical PDF reports (up to {max_pdfs}) ...")

    # Prioritise: 2 per subtype (correct predictions) + remaining
    priority = []
    for s in SUBTYPES:
        mask = (df["True_Subtype"] == s) & (df["Pred_Subtype"] == s)
        top  = df[mask].nlargest(3, "Confidence")
        for _, row in top.iterrows():
            priority.append(row)
    seen  = set(r["Patient_ID"] for r in priority)
    extra = [row for _, row in df.iterrows()
             if row["Patient_ID"] not in seen][:max(0, max_pdfs - len(priority))]
    all_rows = priority[:max_pdfs] + extra[:max(0, max_pdfs - len(priority))]

    generated = 0
    for row in all_rows[:max_pdfs]:
        pid     = row["Patient_ID"]
        subtype = row["Pred_Subtype"]
        fname   = f"{pid}_{subtype.replace('+','p')}_report.pdf"
        out_path = PDF_DIR / fname
        try:
            export_clinical_pdf(row, subtype, out_path)
            generated += 1
            if generated % 5 == 0:
                print(f"  {generated}/{min(len(all_rows), max_pdfs)} reports written ...")
        except Exception as exc:
            print(f"  Warning: {pid} failed -- {exc}")

    print(f"  Done. {generated} PDF reports saved to: {PDF_DIR}")


# ─────────────────────────────────────────────────────────────────────────────
# 8. MAIN
# ─────────────────────────────────────────────────────────────────────────────

def main():
    print("=" * 68)
    print("  Onco-Fusion: WSI-Style Medical Reports Generator")
    print("  Modelled after WSI/src/phase7_llm_report.py")
    print("=" * 68)

    df = load_reports()

    fig50_he_subtype_gallery(df)
    fig51_patient_attention_panels(df)
    fig52_gradcam_overlays(df)
    fig53_multimodal_clinical_dashboard(df)

    generate_all_pdfs(df, max_pdfs=20)

    print("\n" + "=" * 68)
    print("  All outputs generated:")
    print(f"    figures/50_wsi_he_subtype_gallery.png")
    print(f"    figures/51_wsi_patient_attention.png")
    print(f"    figures/52_wsi_gradcam_overlays.png")
    print(f"    figures/53_multimodal_clinical.png")
    print(f"    reports/clinical_wsi/  ({len(list(PDF_DIR.glob('*.pdf')))} PDFs)")
    print("=" * 68)


if __name__ == "__main__":
    main()
